<template>
  <div class="page-card">
    <div class="toolbar"><el-button v-if="isAdmin" type="success" @click="openCreate">新增项目</el-button><el-button @click="load">刷新</el-button></div>
    <el-table :data="rows">
      <el-table-column prop="project_id" label="ID" width="70"/><el-table-column prop="project_name" label="项目名称" min-width="180"/><el-table-column prop="project_code" label="项目编码" min-width="180"/><el-table-column prop="registry" label="镜像仓库" min-width="180"/><el-table-column prop="repository" label="Repository" min-width="220"/><el-table-column prop="default_branch" label="分支" width="100"/><el-table-column prop="status" label="状态" width="100"/>
      <el-table-column label="操作" width="150"><template #default="s"><el-button link type="primary" @click="showImages(s.row)">镜像版本</el-button><el-button v-if="isAdmin" link type="warning" @click="edit(s.row)">编辑</el-button></template></el-table-column>
    </el-table>
    <el-dialog v-model="visible" :title="form.project_id?'编辑项目':'新增项目'" width="620px"><el-form label-width="120px"><el-form-item label="项目名称"><el-input v-model="form.project_name"/></el-form-item><el-form-item label="项目编码"><el-input v-model="form.project_code"/></el-form-item><el-form-item label="Registry"><el-input v-model="form.registry" placeholder="registry.example.com"/></el-form-item><el-form-item label="Repository"><el-input v-model="form.repository" placeholder="crawlers/ulike-overseas-scraper"/></el-form-item><el-form-item label="默认分支"><el-input v-model="form.default_branch"/></el-form-item><el-form-item label="状态"><el-select v-model="form.status"><el-option label="启用" value="ENABLED"/><el-option label="停用" value="DISABLED"/></el-select></el-form-item><el-form-item label="说明"><el-input v-model="form.description" type="textarea"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog>
    <el-drawer v-model="imageVisible" size="75%" title="镜像版本"><div class="toolbar"><el-input v-model="channel.name" placeholder="通道名 stable" style="width:180px"/><el-select v-model="channel.image_version_id" placeholder="选择镜像" style="width:360px"><el-option v-for="i in images" :key="i.image_version_id" :label="`${i.image_tag} / ${i.git_commit}`" :value="i.image_version_id"/></el-select><el-button v-if="isAdmin" type="primary" @click="setChannel">设置发布通道</el-button></div><el-table :data="images"><el-table-column prop="image_tag" label="Tag" min-width="170"/><el-table-column prop="image_digest" label="Digest" min-width="260" show-overflow-tooltip/><el-table-column prop="git_branch" label="分支" width="100"/><el-table-column prop="git_commit" label="Commit" width="140"/><el-table-column prop="pipeline_id" label="流水线" width="100"/><el-table-column prop="build_status" label="状态" width="100"/><el-table-column label="构建时间" width="190"><template #default="s">{{ $dt(s.row.built_at) }}</template></el-table-column></el-table></el-drawer>
  </div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue'; import { ElMessage } from 'element-plus'; import api from '../api'; import { isAdmin } from '../auth'
const rows=ref([]),visible=ref(false),imageVisible=ref(false),images=ref([]),current=ref(null);const form=reactive({project_id:null,project_code:'',project_name:'',registry:'',repository:'',default_branch:'main',status:'ENABLED',description:''});const channel=reactive({name:'stable',image_version_id:null})
async function load(){rows.value=(await api.get('/projects')).data}
function openCreate(){Object.assign(form,{project_id:null,project_code:'',project_name:'',registry:'',repository:'',default_branch:'main',status:'ENABLED',description:''});visible.value=true}
function edit(row){Object.assign(form,row);visible.value=true}
async function save(){const payload={...form};delete payload.project_id;try{if(form.project_id)await api.put(`/projects/${form.project_id}`,payload);else await api.post('/projects',payload);ElMessage.success('保存成功');visible.value=false;load()}catch(e){ElMessage.error(e.response?.data?.detail||'保存失败')}}
async function showImages(row){current.value=row;images.value=(await api.get(`/projects/${row.project_id}/images`)).data;channel.image_version_id=images.value[0]?.image_version_id||null;imageVisible.value=true}
async function setChannel(){try{await api.put(`/projects/${current.value.project_id}/channels/${channel.name}`,null,{params:{image_version_id:channel.image_version_id}});ElMessage.success('发布通道已更新')}catch(e){ElMessage.error(e.response?.data?.detail||'更新失败')}}
onMounted(load)
</script>
