<template><div class="page-card"><el-tabs><el-tab-pane label="密钥管理"><div class="toolbar"><el-button type="success" @click="openSecret">新增密钥</el-button><el-button @click="loadSecrets">刷新</el-button></div><el-table :data="secrets"><el-table-column prop="secret_code" label="密钥编码"/><el-table-column prop="secret_name" label="名称"/><el-table-column prop="description" label="说明" min-width="220"/><el-table-column label="状态" width="100"><template #default="s"><el-tag :type="s.row.enabled?'success':'info'">{{s.row.enabled?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column label="更新时间" width="190"><template #default="s">{{ $dt(s.row.updated_at) }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="editSecret(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane><el-tab-pane label="普通配置"><div class="toolbar"><el-button type="success" @click="openConfig">新增配置</el-button><el-button @click="loadConfigs">刷新</el-button></div><el-table :data="configs"><el-table-column prop="config_key" label="配置键"/><el-table-column prop="config_name" label="名称"/><el-table-column prop="config_value" label="配置值" min-width="220"/><el-table-column prop="description" label="说明"/><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="editConfig(s.row)">编辑</el-button></template></el-table-column></el-table></el-tab-pane></el-tabs>
<el-dialog v-model="secretVisible" title="保存密钥" width="560px"><el-form label-width="110px"><el-form-item label="密钥编码"><el-input v-model="secretForm.secret_code" :disabled="!!secretForm.existing"/></el-form-item><el-form-item label="名称"><el-input v-model="secretForm.secret_name"/></el-form-item><el-form-item label="密钥值"><el-input v-model="secretForm.value" type="password" show-password :placeholder="secretForm.existing?'留空则不修改':'必填'"/></el-form-item><el-form-item label="说明"><el-input v-model="secretForm.description"/></el-form-item><el-form-item label="启用"><el-switch v-model="secretForm.enabled"/></el-form-item></el-form><template #footer><el-button @click="secretVisible=false">取消</el-button><el-button type="primary" @click="saveSecret">保存</el-button></template></el-dialog>
<el-dialog v-model="configVisible" title="保存配置" width="560px"><el-form label-width="110px"><el-form-item label="配置键"><el-input v-model="configForm.config_key" :disabled="!!configForm.existing"/></el-form-item><el-form-item label="名称"><el-input v-model="configForm.config_name"/></el-form-item><el-form-item label="值"><el-input v-model="configForm.config_value" type="textarea"/></el-form-item><el-form-item label="说明"><el-input v-model="configForm.description"/></el-form-item></el-form><template #footer><el-button @click="configVisible=false">取消</el-button><el-button type="primary" @click="saveConfig">保存</el-button></template></el-dialog></div></template>
<script setup>
import { onMounted, reactive, ref } from 'vue';import { ElMessage } from 'element-plus';import api from '../api'
const secrets=ref([]),configs=ref([]),secretVisible=ref(false),configVisible=ref(false);const secretForm=reactive({existing:false,secret_code:'',secret_name:'',value:'',description:'',enabled:true});const configForm=reactive({existing:false,config_key:'',config_name:'',config_value:'',description:''})
async function loadSecrets(){secrets.value=(await api.get('/settings/secrets')).data}async function loadConfigs(){configs.value=(await api.get('/settings/configs')).data}
function openSecret(){Object.assign(secretForm,{existing:false,secret_code:'',secret_name:'',value:'',description:'',enabled:true});secretVisible.value=true}function editSecret(r){Object.assign(secretForm,{existing:true,secret_code:r.secret_code,secret_name:r.secret_name,value:'',description:r.description,enabled:r.enabled});secretVisible.value=true}
async function saveSecret(){try{await api.put(`/settings/secrets/${secretForm.secret_code}`,{secret_name:secretForm.secret_name,value:secretForm.value,description:secretForm.description,enabled:secretForm.enabled});ElMessage.success('保存成功');secretVisible.value=false;loadSecrets()}catch(e){ElMessage.error(e.response?.data?.detail||'保存失败')}}
function openConfig(){Object.assign(configForm,{existing:false,config_key:'',config_name:'',config_value:'',description:''});configVisible.value=true}function editConfig(r){Object.assign(configForm,{existing:true,...r});configVisible.value=true}
async function saveConfig(){await api.put(`/settings/configs/${configForm.config_key}`,configForm);ElMessage.success('保存成功');configVisible.value=false;loadConfigs()}
onMounted(()=>{loadSecrets();loadConfigs()})
</script>
