<template>
  <div class="page-card"><div class="toolbar"><el-button type="success" @click="openCreate">新增用户</el-button><el-button @click="load">刷新</el-button></div><el-table :data="rows"><el-table-column prop="user_id" label="ID" width="70"/><el-table-column prop="user_name" label="账号"/><el-table-column prop="nick_name" label="昵称"/><el-table-column prop="role_type" label="角色"/><el-table-column label="状态"><template #default="s"><el-tag :type="s.row.status?'success':'info'">{{s.row.status?'正常':'停用'}}</el-tag></template></el-table-column><el-table-column label="最后登录" width="190"><template #default="s">{{ $dt(s.row.last_login_at) }}</template></el-table-column><el-table-column label="操作" width="100"><template #default="s"><el-button link type="primary" @click="edit(s.row)">编辑</el-button></template></el-table-column></el-table>
  <el-dialog v-model="visible" :title="form.user_id?'编辑用户':'新增用户'" width="520px"><el-form label-width="100px"><el-form-item label="账号"><el-input v-model="form.user_name" :disabled="!!form.user_id"/></el-form-item><el-form-item label="昵称"><el-input v-model="form.nick_name"/></el-form-item><el-form-item label="密码"><el-input v-model="form.password" type="password" show-password :placeholder="form.user_id?'留空则不修改':'至少8位'"/></el-form-item><el-form-item label="角色"><el-select v-model="form.role_type"><el-option label="超级管理员" value="SUPER_ADMIN"/><el-option label="普通用户" value="NORMAL_USER"/></el-select></el-form-item><el-form-item label="状态"><el-switch v-model="form.status"/></el-form-item></el-form><template #footer><el-button @click="visible=false">取消</el-button><el-button type="primary" @click="save">保存</el-button></template></el-dialog></div>
</template>
<script setup>
import { onMounted, reactive, ref } from 'vue';import { ElMessage } from 'element-plus';import api from '../api'
const rows=ref([]),visible=ref(false);const form=reactive({user_id:null,user_name:'',nick_name:'',password:'',role_type:'NORMAL_USER',status:true})
async function load(){rows.value=(await api.get('/users')).data}function openCreate(){Object.assign(form,{user_id:null,user_name:'',nick_name:'',password:'',role_type:'NORMAL_USER',status:true});visible.value=true}function edit(row){Object.assign(form,row,{password:''});visible.value=true}
async function save(){try{if(form.user_id){const p={nick_name:form.nick_name,role_type:form.role_type,status:form.status};if(form.password)p.password=form.password;await api.put(`/users/${form.user_id}`,p)}else await api.post('/users',form);ElMessage.success('保存成功');visible.value=false;load()}catch(e){ElMessage.error(e.response?.data?.detail||'保存失败')}}onMounted(load)
</script>
